In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,confusion_matrix
from sklearn.preprocessing import LabelEncoder

In [3]:
df=pd.read_csv('/home/nitish/Documents/ML_Projects/Datasets/AI Doctor/Training.csv')

In [4]:
df.head()

itching  skin_rash  nodal_skin_eruptions  continuous_sneezing  shivering  \
0        1          1                     1                    0          0   
1        0          1                     1                    0          0   
2        1          0                     1                    0          0   
3        1          1                     0                    0          0   
4        1          1                     1                    0          0   

   chills  joint_pain  stomach_pain  acidity  ulcers_on_tongue  ...  \
0       0           0             0        0                 0  ...   
1       0           0             0        0                 0  ...   
2       0           0             0        0                 0  ...   
3       0           0             0        0                 0  ...   
4       0           0             0        0                 0  ...   

   blackheads  scurring  skin_peeling  silver_like_dusting  \
0           0         0             0                    0   
1           0         0             0                    0   
2           0         0             0                    0   
3           0         0             0                    0   
4           0         0             0                    0   

   small_dents_in_nails  inflammatory_nails  blister  red_sore_around_nose  \
0                     0                   0        0                     0   
1                     0                   0        0                     0   
2                     0                   0        0                     0   
3                     0                   0        0                     0   
4                     0                   0        0                     0   

   yellow_crust_ooze         prognosis  
0                  0  Fungal infection  
1                  0  Fungal infection  
2                  0  Fungal infection  
3                  0  Fungal infection  
4                  0  Fungal infection  

[5 rows x 133 columns]

In [5]:
df.shape

(4920, 133)

In [6]:
df['prognosis'].unique()

array(['Fungal infection', 'Allergy', 'GERD', 'Chronic cholestasis',
       'Drug Reaction', 'Peptic ulcer diseae', 'AIDS', 'Diabetes ',
       'Gastroenteritis', 'Bronchial Asthma', 'Hypertension ', 'Migraine',
       'Cervical spondylosis', 'Paralysis (brain hemorrhage)', 'Jaundice',
       'Malaria', 'Chicken pox', 'Dengue', 'Typhoid', 'hepatitis A',
       'Hepatitis B', 'Hepatitis C', 'Hepatitis D', 'Hepatitis E',
       'Alcoholic hepatitis', 'Tuberculosis', 'Common Cold', 'Pneumonia',
       'Dimorphic hemmorhoids(piles)', 'Heart attack', 'Varicose veins',
       'Hypothyroidism', 'Hyperthyroidism', 'Hypoglycemia',
       'Osteoarthristis', 'Arthritis',
       '(vertigo) Paroymsal  Positional Vertigo', 'Acne',
       'Urinary tract infection', 'Psoriasis', 'Impetigo'], dtype=object)

In [7]:
X_train,X_test,y_train,y_test=train_test_split(df.iloc[:,0:131],df.iloc[:,-1],test_size=0.2,random_state=10)

In [8]:
encoder=LabelEncoder()

In [9]:
y_train=encoder.fit_transform(y_train)
y_test=encoder.transform(y_test)

In [10]:
y_train

array([36, 39,  1, ..., 30, 26, 33])

In [11]:
from sklearn.datasets import make_classification
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier,GradientBoostingClassifier
from xgboost import XGBClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import MultinomialNB

In [12]:
#We will create a dictonary to store model
models={
    'SVM':SVC(kernel='linear'),
    'RandomForest':RandomForestClassifier(n_estimators=100,random_state=22),
    'GrandientBoosting':GradientBoostingClassifier(n_estimators=100,random_state=22),
    'KNeighbours':KNeighborsClassifier(n_neighbors=5),
    'MultinomialNB':MultinomialNB(),
    'Xgboost':XGBClassifier()
}


In [13]:
for model_name,model in models.items():
    model.fit(X_train,y_train)
    y_pred=model.predict(X_test)
    print(model_name)
    print(accuracy_score(y_test,y_pred))
    print(confusion_matrix(y_test,y_pred))
    
    

SVM
1.0
[[22  0  0 ...  0  0  0]
 [ 0 23  0 ...  0  0  0]
 [ 0  0 24 ...  0  0  0]
 ...
 [ 0  0  0 ... 26  0  0]
 [ 0  0  0 ...  0 20  0]
 [ 0  0  0 ...  0  0 30]]
RandomForest
1.0
[[22  0  0 ...  0  0  0]
 [ 0 23  0 ...  0  0  0]
 [ 0  0 24 ...  0  0  0]
 ...
 [ 0  0  0 ... 26  0  0]
 [ 0  0  0 ...  0 20  0]
 [ 0  0  0 ...  0  0 30]]
GrandientBoosting
1.0
[[22  0  0 ...  0  0  0]
 [ 0 23  0 ...  0  0  0]
 [ 0  0 24 ...  0  0  0]
 ...
 [ 0  0  0 ... 26  0  0]
 [ 0  0  0 ...  0 20  0]
 [ 0  0  0 ...  0  0 30]]
KNeighbours
1.0
[[22  0  0 ...  0  0  0]
 [ 0 23  0 ...  0  0  0]
 [ 0  0 24 ...  0  0  0]
 ...
 [ 0  0  0 ... 26  0  0]
 [ 0  0  0 ...  0 20  0]
 [ 0  0  0 ...  0  0 30]]
MultinomialNB
1.0
[[22  0  0 ...  0  0  0]
 [ 0 23  0 ...  0  0  0]
 [ 0  0 24 ...  0  0  0]
 ...
 [ 0  0  0 ... 26  0  0]
 [ 0  0  0 ...  0 20  0]
 [ 0  0  0 ...  0  0 30]]
Xgboost
1.0
[[22  0  0 ...  0  0  0]
 [ 0 23  0 ...  0  0  0]
 [ 0  0 24 ...  0  0  0]
 ...
 [ 0  0  0 ... 26  0  0]
 [ 0  0  0 ...  0 20  

In [15]:
svc=SVC(kernel='linear')
svc.fit(X_test,y_test)
y_pred=svc.predict(X_test)
accuracy_score(y_test,y_pred)

1.0